export const ROUTES = {
  HOME: '/',
  ACCOUNT: {
    ROOT: '/account',
    PROFILE: '/account/profile',
    WISH_LIST: '/account/wishlist',
    ORDER: '/account/order',
    REFUND: '/account/refund',
  },
  ADMIN: {
    ROOT: '/admin',
    USERS: '/admin/users',
    CUSTOMERS: '/admin/customers',
    PARTNERS: '/admin/partners',
    HOTELS: '/admin/hotels',
    ORDERS: '/admin/orders',
    COUPONS: '/admin/coupons',
    PROMOTIONS: '/admin/promotions',
    TRANSACTIONS: '/admin/transactions',
    REFUNDS: '/admin/refunds',
    REVIEWS: '/admin/reviews',
    NOTIFICATIONS: '/admin/notifications',
    PROFILE: '/admin/profile',
  },
  PARTNER: {
    ROOT: '/partner',
    DASHBOARD: '/partner',
    PROFILE: '/partner/profile',
    HOTEL: '/partner/hotel',
    AMENITIES: '/partner/amenities',
    ROOM_TYPES: '/partner/room-types',
    ROOM_TYPES_CREATE: '/partner/room-types/create',
    ROOMS: '/partner/rooms',
    ORDERS: '/partner/orders',
  },
  TWO_FA_PAGE: '/2fa-page',
  RESET_PASSWORD_PAGE: '/reset-password',
  BECOME_PARTNER: {
    ROOT: '/become-partner',
    PARTNER: '/become-partner/partner',
    HOTEL: '/become-partner/hotel',
  },
};
