export const ROUTES = {
  HOME: '/',
  ACCOUNT: {
    ROOT: '/account',
    PROFILE: '/account/profile',
    WISH_LIST: '/account/wishlist',
    ORDER: '/account/order',
    REFUND: '/account/refund',
    APPLIED_PARTNER: '/account/applied-partner',
  },
  ADMIN: {
    ROOT: '/admin',
    USERS: '/admin/users',
    CUSTOMERS: '/admin/customers',
    PARTNERS: '/admin/partners',
    HOTELS: '/admin/hotels',
    ORDERS: '/admin/orders',
    COUPONS: '/admin/coupons',
    PROMOTIONS: '/admin/promotions',
    TRANSACTIONS: '/admin/transactions',
    REFUNDS: '/admin/refunds',
    REVIEWS: '/admin/reviews',
    NOTIFICATIONS: '/admin/notifications',
    PROFILE: '/admin/profile',
  },
  PARTNER: {
    ROOT: '/partner',
    HOTELS: '/partner/hotels',
    ROOMS: '/partner/rooms',
    ORDERS: '/partner/orders',
  },
  TWO_FA_PAGE: '/2fa-page',
  RESET_PASSWORD_PAGE: '/reset-password',
};
